services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    networks:
      - internal
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=grafana
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: always
    networks:
      - internal
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/grafana-data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/rsa_pub.pem:/etc/grafana/rsa_pub.pem
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana_admin

networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.32.0.0/16
